#!/usr/bin/env python3
"""Create a file from a qwen35-9b completion via local llama-server."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib import request


DEFAULT_API_URL = "http://127.0.0.1:8001/v1/chat/completions"


def call_llama(api_url: str, prompt: str, max_tokens: int = 256) -> str:
    payload = {
        "model": "qwen35-9b",
        "messages": [
            {
                "role": "system",
                "content": "You are a coding assistant that writes concise, plain-text files.",
            },
            {"role": "user", "content": prompt},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.2,
        "top_p": 0.9,
        "top_k": 20,
    }

    req = request.Request(
        api_url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    with request.urlopen(req, timeout=180) as resp:
        body = json.loads(resp.read().decode("utf-8"))

    return body.get("choices", [{}])[0].get("message", {}).get("content", "").strip()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--api-url",
        default=DEFAULT_API_URL,
        help="llama-server chat-completions endpoint",
    )
    parser.add_argument("--output", default="hello.txt")
    args = parser.parse_args()

    prompt = (
        "Create a file content for hello.txt. The output must be exactly the file body only. "
        "Write 1-2 short lines that clearly state: This file was generated by qwen35-9b."
    )

    content = call_llama(args.api_url, prompt, max_tokens=128)

    out_path = Path(args.output)
    out_path.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"wrote:{out_path}")


if __name__ == "__main__":
    main()
